services:
  db:
    image: public.ecr.aws/docker/library/postgres:16-alpine
    environment:
      POSTGRES_DB: grupo
      POSTGRES_USER: grupo
      POSTGRES_PASSWORD: grupo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grupo"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://grupo:grupo@db:5432/grupo}
    ports:
      - "8090:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/backend/app

volumes:
  pgdata:

